version: '3'
services:
  master:
    build: .
    hostname: master
    networks:
      cluster_net:
        ipv4_address: 192.168.10.2
    extra_hosts:
      - "datanode1:192.168.10.3"
      - "datanode2:192.168.10.4"
  datanode1:
    build: .
    hostname: datanode1
    networks:
      cluster_net:
        ipv4_address: 192.168.10.3
    extra_hosts:
      - "master:192.168.10.2"
      - "datanode2:192.168.10.4"
  datanode2:
    build: .
    hostname: datanode2
    networks:
      cluster_net:
        ipv4_address: 192.168.10.4
    extra_hosts:
      - "datanode1:192.168.10.3"
      - "master:192.168.10.2"

networks:
  cluster_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
